---
Name: fromholdio-systemlinks
---

SilverStripe\Admin\ModalController:
  extensions:
    - Fromholdio\SystemLinks\Extensions\SystemLinkModalExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Fromholdio\SystemLinks\Extensions\SystemLinksLeftAndMainExtension
